-- Copparì · migrazione per il ciclo annuale
-- Eseguire nel SQL Editor di Supabase sui progetti già configurati.

create table if not exists public.coppari_live_editions (
  id bigint generated by default as identity primary key,
  room_id text not null references public.coppari_live_tournaments(room_id) on delete cascade,
  edition_label text not null,
  state jsonb not null,
  closed_at timestamptz not null default now(),
  unique (room_id, edition_label),
  constraint coppari_live_edition_label_length check (char_length(edition_label) between 1 and 80),
  constraint coppari_live_edition_state_object check (jsonb_typeof(state) = 'object')
);

alter table public.coppari_live_editions enable row level security;
revoke all on table public.coppari_live_editions from public, anon, authenticated;

create or replace function public.coppari_live_stop(
  p_room_id text,
  p_manager_secret text
)
returns boolean
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  v_row public.coppari_live_tournaments%rowtype;
  v_edition_label text;
begin
  select tournament.* into v_row
  from public.coppari_live_tournaments as tournament
  where tournament.room_id = p_room_id
  for update;

  if not found then
    return false;
  end if;
  if v_row.manager_secret_hash <> digest(coalesce(p_manager_secret, ''), 'sha256') then
    raise exception 'LIVE_ACCESS_DENIED';
  end if;
  if not v_row.active then
    return true;
  end if;

  v_edition_label := left(coalesce(nullif(v_row.state #>> '{settings,edition}', ''), 'Edizione ' || to_char(now(), 'YYYY')), 80);
  insert into public.coppari_live_editions (room_id, edition_label, state, closed_at)
  values (v_row.room_id, v_edition_label, v_row.state, now())
  on conflict (room_id, edition_label)
  do update set state = excluded.state, closed_at = excluded.closed_at;

  update public.coppari_live_tournaments as tournament
  set active = false,
      revision = tournament.revision + 1,
      updated_at = now()
  where tournament.room_id = p_room_id;
  return true;
end;
$$;

create or replace function public.coppari_live_start_edition(
  p_room_id text,
  p_manager_secret text,
  p_state jsonb
)
returns table (
  revision bigint,
  state jsonb,
  active boolean,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  v_row public.coppari_live_tournaments%rowtype;
  v_edition_label text;
begin
  if jsonb_typeof(p_state) <> 'object' or octet_length(p_state::text) > 2000000 then
    raise exception 'LIVE_STATE_INVALID';
  end if;

  select tournament.* into v_row
  from public.coppari_live_tournaments as tournament
  where tournament.room_id = p_room_id
  for update;

  if not found then
    raise exception 'LIVE_ROOM_NOT_FOUND';
  end if;
  if v_row.manager_secret_hash <> digest(coalesce(p_manager_secret, ''), 'sha256') then
    raise exception 'LIVE_ACCESS_DENIED';
  end if;
  if v_row.active then
    raise exception 'LIVE_ALREADY_ACTIVE';
  end if;

  v_edition_label := left(coalesce(nullif(v_row.state #>> '{settings,edition}', ''), 'Edizione ' || to_char(now(), 'YYYY')), 80);
  insert into public.coppari_live_editions (room_id, edition_label, state, closed_at)
  values (v_row.room_id, v_edition_label, v_row.state, now())
  on conflict (room_id, edition_label)
  do update set state = excluded.state, closed_at = excluded.closed_at;

  update public.coppari_live_tournaments as tournament
  set state = p_state,
      active = true,
      revision = tournament.revision + 1,
      updated_at = now()
  where tournament.room_id = p_room_id
  returning tournament.* into v_row;

  return query
  select v_row.revision, v_row.state, v_row.active, v_row.updated_at;
end;
$$;

revoke all on function public.coppari_live_stop(text, text) from public;
revoke all on function public.coppari_live_start_edition(text, text, jsonb) from public;
grant execute on function public.coppari_live_stop(text, text) to anon, authenticated;
grant execute on function public.coppari_live_start_edition(text, text, jsonb) to anon, authenticated;

comment on table public.coppari_live_editions is
  'Archivio delle edizioni annuali Copparì, accessibile soltanto tramite RPC dedicate.';
